apps/authenticate/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^success$', views.success, name = 'success'),
    url(r'^logout$', views.logout, name = 'logout'),
    url(r'^login$', views.login, name = 'login')
]

login_registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.authenticate.urls', namespace = 'auth'))
]

apps/authenticate/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import datetime

class UserManager(models.Manager):
    
    def validate(self, post):
    
        errors = {}

        fname = post['first_name']
        if not fname.isalpha():
            errors['fname_alpha'] = 'First name must be only alphabetical characters'
        if not len(fname) >= 2:
            errors['fname_len'] = 'First name must be 2 or more characters'   

        lname = post['last_name']
        if not lname.isalpha():
            errors['lname_alpha'] = 'Last name must be only alphabetical characters'
        if not len(lname) >= 2: 
            errors['lname_len'] = 'Last name must be 2 or more characters'

        password = post['password']
        if not password == post['confirm_password']:
            errors['pw_mismatch'] = 'Passwords must match'
        if not len(password) >= 8:
            errors['pw_len'] = 'Password must be 8 or more characters'

        try:
            validate_email(post['email'])
        except ValidationError:
            errors['email_format'] = 'Email must be a valid address'
        else:
            if not errors:
                if User.objects.filter(email = post['email']):
                    errors['email_unique'] = 'User already exists'

                
        return errors                


class User(models.Model):
    
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/authenticate/forms.py
from django.forms import ModelForm, forms, PasswordInput, DateInput, CharField
from .models import User

class UserForm(ModelForm):   
    
    confirm_password = CharField(widget=PasswordInput())
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {
            'password' : PasswordInput,
        }


    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        

apps/authenticate/views.py
from django.shortcuts import render, redirect
from django import forms
from django.contrib import messages
from django.core.urlresolvers import reverse
from .forms import UserForm
from .models import User
import bcrypt

def index(request):
 
    if request.method == 'GET':
        if 'user' in request.session:
            return redirect(reverse('auth:success'))
        return render(request, 'authenticate/index.html', { 'form' : UserForm() })
                
def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        errors = User.objects.validate(request.POST)
        if errors:
            for tag, error in errors.iteritems():
                messages.error(request, error)
            return redirect(reverse('auth:index'))
        else:
            user = form.save(commit=False)
            user.password = bcrypt.hashpw(user.password.encode(), bcrypt.gensalt())
            user.save()
            request.session['user'] = '{} {}'.format(user.first_name, user.last_name)
            messages.success(request, 'Successfully registerd and logged in.')            
            return redirect(reverse('auth:success'))                 

def login(request):

    email = request.POST['email']
    password = request.POST['password']

    user = User.objects.filter(email = email).first()

    if user:
        valid_pw = bcrypt.checkpw(password.encode(), user.password.encode())
        if valid_pw:
            request.session['user'] = '{} {}'.format(user.first_name, user.last_name)
            messages.success(request, 'Successfully registerd and logged in.')             
            return redirect(reverse('auth:success'))
        else:
            messages.error(request, 'Invalid user/password')
            return redirect(reverse('auth:index'))                            
    else:
        messages.error(request, 'User does not exist')
        return redirect(reverse('auth:index'))        
    
                   
def success(request):

    return render(request, 'authenticate/success.html')
    

def logout(request):           

    user = request.session['user']             
    request.session.clear()
    messages.success(request, '{} has been logged out'.format(user))
    return redirect(reverse('auth:index'))

apps/authenticate/templates/authenticate/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
        <title>Users {% block title%}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <script type="text/javascript">
            $(document).ready(function() {
                {% block jquery %}
                {% endblock %}
            });
        </script>
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
            {% block footer %}
            {% endblock %}
        </div>
    </body>
</html>

apps/authenticate/templates/authenticate/index.html
{% extends 'authenticate/base.html' %}

{% block content %}
    {% if messages %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <ul>
            {% for message in messages %}
                <li class="{% if message.tags %}{% if message.tags == 'error' %}text-danger{% else %}text-success{% endif %}{% endif %}">{{ message }}</li>
            {% endfor%}
            </ul>
         </div>
        <div class="col"></div>        
    </div>        
    {% endif %}
    <div class="row border border-dark rounded p-3 mt-3">
        <div class="col"></div>
        <div class="col-6">
            <h1>Register</h1>
            <form action="{% url 'auth:register' %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                    <button type="submit" class="btn btn-primary float-right">Register</button>
            </form>
        </div>
        <div class="col"></div>        
    </div>     
    <div class="row border border-dark rounded p-3 mt-3"> 
        <div class="col"></div>
        <div class="col-6 mt-3">
            <h1>Login</h1>
            <form action="{% url 'auth:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" name="email" class="form-control">              
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary float-right">Login</button>
            </form>
        </div>
    <div class="col"></div> 
    </div>
{% endblock %}

apps/authenticate/templates/authenticate/success.html
{% extends 'authenticate/base.html' %}

{% block content %}
    <h1>Success! Welcome, {{ request.session.user }}</h1>
    {% for message in messages %}
        <p class="text-success">{{ message }}</p>
    {% endfor %}
{% endblock %}

{% block footer %}
    <a href="{% url 'auth:logout' %}" class="btn btn-dark">Logout</a>
{% endblock %}